@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "Main",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_2390489 { 
   	label=Main
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Main2390489[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Main</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ main(args: String[])</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_72806857 { 
   	label=Entidad
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Armadura72806857[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Armadura</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   botas: Bota [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   guantes: Guante [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   reactor: Reactor [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ caminar()</TD></TR>
<TR><TD ALIGN="LEFT" >+ correr()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Bota72806857[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Bota</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   consumo: float [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   destruido: boolean [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   propulsorBota: Propulsor [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   sano: boolean [1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Guante72806857[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Guante</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   consumo: float [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   destruido: boolean [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   propulsorGuante: Propulsor [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   sano: boolean [1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Propulsor72806857[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Propulsor</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   consumo: float [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   destruido: boolean [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   sano: boolean [1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Reactor72806857[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Reactor</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   cargaReactor: float [1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

'edges    
Armadura72806857 -> Bota72806857[label="botas
[0..1]"];
Armadura72806857 -> Guante72806857[label="guantes
[0..1]"];
Armadura72806857 -> Reactor72806857[label="reactor
[0..1]"];
Bota72806857 -> Propulsor72806857[label="propulsorBota
[0..1]"];
Guante72806857 -> Propulsor72806857[label="propulsorGuante
[0..1]"];
    
}
@enduml